import "./globals.css"

import { Inter } from "next/font/google"
import type { Metadata } from "next"
import { ModalProvider } from "@/providers/modal-provider"
import { Toaster } from "sonner"
import { validateEnv } from "@/lib/safetyChecks"
import Script from "next/script"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Pay with Braintree",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    validateEnv()

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <ModalProvider />
                <Toaster />
                <Script src="https://js.braintreegateway.com/web/3.101.0/js/client.min.js" />
                <Script src="https://js.braintreegateway.com/web/3.101.0/js/venmo.min.js" />
                <Script src="https://js.braintreegateway.com/web/3.101.0/js/data-collector.min.js" />
                {children}
            </body>
        </html>
    )
}
